package com.levi.common.constant;

public final class QueryConstants {

    private QueryConstants() {
    }

    public static final String ORDER_DETAILS_UPSERT = "INSERT INTO order_details "
            + "(sales_document_number, sales_org, sold_to, sales_document_type, "
            + "sales_document_date, purchase_order_type, purchase_order_number, planning_group, order_reason, "
            + "region, country_code, customer_name, order_status, "
            + "tax, amount, invoice_number, tracking_number, "
            + "discount, is_valid, create_ts, create_user, modify_ts, modify_user)"
            + " values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
            + " ON CONFLICT (sales_document_number) DO UPDATE SET sales_org=EXCLUDED.sales_org,"
            + "sold_to=EXCLUDED.sold_to, sales_document_type=EXCLUDED.sales_document_type, sales_document_date=EXCLUDED.sales_document_date,"
            + "purchase_order_type=EXCLUDED.purchase_order_type, purchase_order_number=EXCLUDED.purchase_order_number, "
            + "planning_group=EXCLUDED.planning_group, order_reason=EXCLUDED.order_reason, "
            + "region=EXCLUDED.region, country_code=EXCLUDED.country_code, "
            + "customer_name=EXCLUDED.customer_name, order_status=EXCLUDED.order_status, tax=EXCLUDED.tax, amount=EXCLUDED.amount, "
            + "invoice_number=EXCLUDED.invoice_number, tracking_number=EXCLUDED.tracking_number, "
            + "discount=EXCLUDED.discount, is_valid=EXCLUDED.is_valid, "
            + "modify_ts=EXCLUDED.modify_ts, modify_user=EXCLUDED.modify_user";

    public static final String LINE_ENTRY_UPSERT = "INSERT INTO line_entry "
            + "(line_entry_id, sales_document_number, material_code, line_item, item_category, "
            + "consumer_group, material_name, plant, stock_type, brand, currency, wholesale_price, "
            + "wholesale_price_valid_from, wholesale_price_valid_to, discounts, gross_value, expected_price_edi, "
            + "levi_retail_price, customer_expc_msrp, rpm_price, net_value, net_price, quantity, description, "
            + "sub_total, line_item_status, "
            + "cancelled_quantity, create_ts, create_user, modify_ts, modify_user) "
            + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) "
            + " ON CONFLICT (line_entry_id) DO UPDATE SET sales_document_number=EXCLUDED.sales_document_number, "
            + "material_code=EXCLUDED.material_code, line_item=EXCLUDED.line_item, item_category=EXCLUDED.item_category, "
            + "consumer_group=EXCLUDED.consumer_group, material_name=EXCLUDED.material_name, plant=EXCLUDED.plant, "
            + "stock_type=EXCLUDED.stock_type, brand=EXCLUDED.brand, currency=EXCLUDED.currency, wholesale_price=EXCLUDED.wholesale_price, "
            + "wholesale_price_valid_from=EXCLUDED.wholesale_price_valid_from, wholesale_price_valid_to=EXCLUDED.wholesale_price_valid_to, "
            + "discounts=EXCLUDED.discounts, gross_value=EXCLUDED.gross_value, expected_price_edi=EXCLUDED.expected_price_edi, "
            + "levi_retail_price=EXCLUDED.levi_retail_price, customer_expc_msrp=EXCLUDED.customer_expc_msrp, rpm_price=EXCLUDED.rpm_price, "
            + "net_value=EXCLUDED.net_value, net_price=EXCLUDED.net_price, quantity=EXCLUDED.quantity, description=EXCLUDED.description, "
            + "sub_total=EXCLUDED.sub_total, line_item_status=EXCLUDED.line_item_status, "
            + "cancelled_quantity=EXCLUDED.cancelled_quantity, "
            + "modify_ts=EXCLUDED.modify_ts, modify_user=EXCLUDED.modify_user ";

    public static final String SCH_LINE_ENTRY_UPSERT = "INSERT INTO schedule_line_entry "
            + "(id, line_entry_id, sales_document_number, line_item, sch_line_item, material_code, "
            + "ordered_quantity, confirmed_quantity, shipped_quantity,\"size\", delivery_date, cancel_date, "
            + "requested_delivery_date, approx_due_in_date, rejection_reason_code, cancelled_sku_qty, "
            + "unit_of_measurement, ship_to, store_name, pac_unconfirmed_quantity, vir_unconfirmed_quantity, "
            + "schedule_status, ship_date, invoice_doc, invoice_date, rejection_reason_description, "
            + "open_qty, fixed_qty, del_ind, create_ts, create_user, modify_ts, modify_user)"
            + " values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
            + " ON CONFLICT (id) DO UPDATE SET line_entry_id=EXCLUDED.line_entry_id, "
            + "sales_document_number=EXCLUDED.sales_document_number, "
            + "line_item=EXCLUDED.line_item, "
            + " sch_line_item=EXCLUDED.sch_line_item, "
            + "material_code=EXCLUDED.material_code, "
            + "ordered_quantity=EXCLUDED.ordered_quantity, "
            + "confirmed_quantity=EXCLUDED.confirmed_quantity, "
            + "shipped_quantity=EXCLUDED.shipped_quantity, "
            + "\"size\"=EXCLUDED.\"size\", "
            + "delivery_date=EXCLUDED.delivery_date, "
            + "cancel_date=EXCLUDED.cancel_date, "
            + "requested_delivery_date=EXCLUDED.requested_delivery_date, "
            + "approx_due_in_date=EXCLUDED.approx_due_in_date, "
            + "rejection_reason_code=EXCLUDED.rejection_reason_code, "
            + "cancelled_sku_qty=EXCLUDED.cancelled_sku_qty, "
            + "unit_of_measurement=EXCLUDED.unit_of_measurement, "
            + "ship_to=EXCLUDED.ship_to, "
            + "store_name=EXCLUDED.store_name, "
            + "pac_unconfirmed_quantity=EXCLUDED.pac_unconfirmed_quantity, "
            + "vir_unconfirmed_quantity=EXCLUDED.vir_unconfirmed_quantity, "
            + "schedule_status=EXCLUDED.schedule_status, "
            + "ship_date=EXCLUDED.ship_date, "
            + "invoice_doc=EXCLUDED.invoice_doc, "
            + "invoice_date=EXCLUDED.invoice_date, "
            + "rejection_reason_description=EXCLUDED.rejection_reason_description, "
            + "open_qty=EXCLUDED.open_qty, "
            + "fixed_qty=EXCLUDED.fixed_qty, "
            + "del_ind=EXCLUDED.del_ind, "
            + "modify_ts=EXCLUDED.modify_ts, "
            + "modify_user=EXCLUDED.modify_user ";

    public static final String ERROR_UPSERT = "INSERT INTO error_details "
            + "(id, sales_document_number, sales_org, sold_to, customer_name, purchase_order_number, "
            + "brand, sales_document_date, currency, order_status, tax, amount, sales_document_type, "
            + "purchase_order_type, order_reason, invoice_number, ship_to, tracking_number, delivery_date, "
            + "discount, region, country_code, material_code, line_item, item_category, consumer_group, "
            + "material_name, plant, stock_type, quantity, wholesale_price, description, "
            + "confirmed_quantity, shipped_quantity, sub_total, line_item_status, "
            + "del_ind, cancelled_quantity, sch_line_item, ordered_quantity, \"size\", "
            + "schedule_status, approx_due_in_date, ship_date, invoice_doc, invoice_date, rejection_reason_code, "
            + "rejection_reason_description, cancelled_sku_qty, open_qty, fixed_qty, store_name, "
            + "cancel_date, unit_of_measurement, requested_delivery_date, error_msg, planning_group, "
            + "wholesale_price_valid_from, wholesale_price_valid_to, discounts, gross_value, expected_price_edi, "
            + "levi_retail_price, customer_expc_msrp, rpm_price, net_value, net_price, pac_unconfirmed_quantity, vir_unconfirmed_quantity, "
            + "is_processed, create_ts, create_user, modify_ts, modify_user) "
            + "values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
            + "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) "
            + "ON CONFLICT (id) DO UPDATE SET "
            + "sales_document_number=EXCLUDED.sales_document_number, sales_org=EXCLUDED.sales_org, "
            + "sold_to=EXCLUDED.sold_to, customer_name=EXCLUDED.customer_name, purchase_order_number=EXCLUDED.purchase_order_number, "
            + "brand=EXCLUDED.brand, sales_document_date=EXCLUDED.sales_document_date, currency=EXCLUDED.currency, "
            + "order_status=EXCLUDED.order_status, tax=EXCLUDED.tax, amount=EXCLUDED.amount, sales_document_type=EXCLUDED.sales_document_type, "
            + "purchase_order_type=EXCLUDED.purchase_order_type, order_reason=EXCLUDED.order_reason, invoice_number=EXCLUDED.invoice_number, "
            + "ship_to=EXCLUDED.ship_to, tracking_number=EXCLUDED.tracking_number, delivery_date=EXCLUDED.delivery_date, "
            + "discount=EXCLUDED.discount, region=EXCLUDED.region, country_code=EXCLUDED.country_code, material_code=EXCLUDED.material_code, "
            + "line_item=EXCLUDED.line_item, item_category=EXCLUDED.item_category, consumer_group=EXCLUDED.consumer_group, "
            + "material_name=EXCLUDED.material_name, plant=EXCLUDED.plant, stock_type=EXCLUDED.stock_type, quantity=EXCLUDED.quantity, "
            + "wholesale_price=EXCLUDED.wholesale_price, description=EXCLUDED.description, "
            + "confirmed_quantity=EXCLUDED.confirmed_quantity, shipped_quantity=EXCLUDED.shipped_quantity, sub_total=EXCLUDED.sub_total, "
            + "line_item_status=EXCLUDED.line_item_status, del_ind=EXCLUDED.del_ind, cancelled_quantity=EXCLUDED.cancelled_quantity, "
            + "sch_line_item=EXCLUDED.sch_line_item, ordered_quantity=EXCLUDED.ordered_quantity, \"size\"=EXCLUDED.\"size\", "
            + "schedule_status=EXCLUDED.schedule_status, approx_due_in_date=EXCLUDED.approx_due_in_date, ship_date=EXCLUDED.ship_date, "
            + "invoice_doc=EXCLUDED.invoice_doc, invoice_date=EXCLUDED.invoice_date, rejection_reason_code=EXCLUDED.rejection_reason_code, "
            + "rejection_reason_description=EXCLUDED.rejection_reason_description, cancelled_sku_qty=EXCLUDED.cancelled_sku_qty, "
            + "open_qty=EXCLUDED.open_qty, fixed_qty=EXCLUDED.fixed_qty, store_name=EXCLUDED.store_name, "
            + "cancel_date=EXCLUDED.cancel_date, unit_of_measurement=EXCLUDED.unit_of_measurement, "
            + "requested_delivery_date=EXCLUDED.requested_delivery_date, error_msg=EXCLUDED.error_msg, planning_group=EXCLUDED.planning_group, "
            + "wholesale_price_valid_from=EXCLUDED.wholesale_price_valid_from, wholesale_price_valid_to=EXCLUDED.wholesale_price_valid_to, "
            + "discounts=EXCLUDED.discounts, gross_value=EXCLUDED.gross_value, expected_price_edi=EXCLUDED.expected_price_edi, "
            + "levi_retail_price=EXCLUDED.levi_retail_price, customer_expc_msrp=EXCLUDED.customer_expc_msrp, "
            + "rpm_price=EXCLUDED.rpm_price, net_value=EXCLUDED.net_value, net_price=EXCLUDED.net_price, "
            + "pac_unconfirmed_quantity=EXCLUDED.pac_unconfirmed_quantity, vir_unconfirmed_quantity=EXCLUDED.vir_unconfirmed_quantity, "
            + "is_processed=EXCLUDED.is_processed, "
            + "modify_ts=EXCLUDED.modify_ts, modify_user=EXCLUDED.modify_user";
}
